Added motor check
shadow-robot/sr_tools pull request #56
Opened 2022-09-05 13:23 UTC by maxzieba

## Proposed changes

User Story: https://shadowrobot.atlassian.net/browse/SP-380
Added motor check to health metrics.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [X] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [X] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-09-06 12:33 UTC, bdenoun requested changes

2022-09-06 12:33 UTC, bdenoun commented on sr_hand_health_report/src/sr_hand_health_report/motor_check.py
> +# with this program. If not, see <http://www.gnu.org/licenses/>.
add extra line here please

2022-09-06 12:33 UTC, bdenoun commented on sr_hand_health_report/src/sr_hand_health_report/motor_check.py
> +        try:
This try seems a bit overkilled... especially for the exception message you want to send. Why not simply wrap the wait_for_message line only and catching the proper exception only?! https://docs.ros.org/en/diamondback/api/rospy/html/rospy.client-module.html#wait_for_message

2022-09-06 14:18 UTC, bdenoun approved these changes

2022-09-12 12:44 UTC, rnzenha-s commented on sr_hand_health_report/src/sr_hand_health_report/calibration_check.py
> +        #super().__init__(hand_side, fingers_to_test)
Don't you need this to initialise `self.fingers_to_check`?

2022-09-20 09:26 UTC, rnzenha-s approved these changes

2022-09-20 13:48 UTC, merged